### PR TITLE
Css canvas medical Jacob Yi

### PR DESCRIPTION
**Pull request by Yi-Jacob**
Screen Shot 2022-02-01 at 8 19 00 PM
Screen Shot 2022-02-01 at 8 18 54 PM
Screen Shot 2022-02-01 at 8 18 46 PM

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Jacob, your output does not match the example in multiple ways, such as the borders of your buttons which are incorrect, the button in the navbar has the text "Contact" rather than "Contact Us", and much of the text is the wrong color, the wrong font family, or both. It is **_vitally important_** that you are turning in work that matches the example given. I have had to return each CSS challenge to you at least once because of aspects that don't match the example, make sure you are comparing your output and the example side-by-side and **_deeply_** scrutinizing it before submitting. I know it is a skill that takes time to master, but you definitely don't want to drop incomplete tasks on your supervisor's desk on the job and make them figure out what's wrong with it.

**Comment by Yi-Jacob** [comment]
Screen Shot 2022-02-05 at 5 03 24 PM
Screen Shot 2022-02-05 at 5 03 14 PM
Screen Shot 2022-02-05 at 5 03 07 PM

**Comment by Yi-Jacob** [comment]
_Users_jacobyi_repos_c0122-code-solutions_css-canvas-medical_index html (1)

**Review by codingcodymiller — APPROVED** [review]
Nice work!

**Pull request merged**
